unsigned int cameraHandle;
int* lensNumber;
double focus;
int* fileArray;
int* currPosition;
static int maxAdapters;
char file;
const char* command;
char* returnVal;
int comStatus;
char* buffer;
int* focusMax;
int fileDescriptor;
int status;